export const initialData = [
    {
    login: "mikeal",
    id: 579,
    node_id: "MDQ6VXNlcjU3OQ==",
    avatar_url: "https://avatars2.githubusercontent.com/u/579?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mikeal",
    html_url: "https://github.com/mikeal",
    followers_url: "https://api.github.com/users/mikeal/followers",
    following_url: "https://api.github.com/users/mikeal/following{/other_user}",
    gists_url: "https://api.github.com/users/mikeal/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mikeal/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mikeal/subscriptions",
    organizations_url: "https://api.github.com/users/mikeal/orgs",
    repos_url: "https://api.github.com/users/mikeal/repos",
    events_url: "https://api.github.com/users/mikeal/events{/privacy}",
    received_events_url: "https://api.github.com/users/mikeal/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "stefanpenner",
    id: 1377,
    node_id: "MDQ6VXNlcjEzNzc=",
    avatar_url: "https://avatars2.githubusercontent.com/u/1377?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/stefanpenner",
    html_url: "https://github.com/stefanpenner",
    followers_url: "https://api.github.com/users/stefanpenner/followers",
    following_url: "https://api.github.com/users/stefanpenner/following{/other_user}",
    gists_url: "https://api.github.com/users/stefanpenner/gists{/gist_id}",
    starred_url: "https://api.github.com/users/stefanpenner/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/stefanpenner/subscriptions",
    organizations_url: "https://api.github.com/users/stefanpenner/orgs",
    repos_url: "https://api.github.com/users/stefanpenner/repos",
    events_url: "https://api.github.com/users/stefanpenner/events{/privacy}",
    received_events_url: "https://api.github.com/users/stefanpenner/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "AArnott",
    id: 3548,
    node_id: "MDQ6VXNlcjM1NDg=",
    avatar_url: "https://avatars2.githubusercontent.com/u/3548?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AArnott",
    html_url: "https://github.com/AArnott",
    followers_url: "https://api.github.com/users/AArnott/followers",
    following_url: "https://api.github.com/users/AArnott/following{/other_user}",
    gists_url: "https://api.github.com/users/AArnott/gists{/gist_id}",
    starred_url: "https://api.github.com/users/AArnott/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/AArnott/subscriptions",
    organizations_url: "https://api.github.com/users/AArnott/orgs",
    repos_url: "https://api.github.com/users/AArnott/repos",
    events_url: "https://api.github.com/users/AArnott/events{/privacy}",
    received_events_url: "https://api.github.com/users/AArnott/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "subtleGradient",
    id: 4117,
    node_id: "MDQ6VXNlcjQxMTc=",
    avatar_url: "https://avatars2.githubusercontent.com/u/4117?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/subtleGradient",
    html_url: "https://github.com/subtleGradient",
    followers_url: "https://api.github.com/users/subtleGradient/followers",
    following_url: "https://api.github.com/users/subtleGradient/following{/other_user}",
    gists_url: "https://api.github.com/users/subtleGradient/gists{/gist_id}",
    starred_url: "https://api.github.com/users/subtleGradient/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/subtleGradient/subscriptions",
    organizations_url: "https://api.github.com/users/subtleGradient/orgs",
    repos_url: "https://api.github.com/users/subtleGradient/repos",
    events_url: "https://api.github.com/users/subtleGradient/events{/privacy}",
    received_events_url: "https://api.github.com/users/subtleGradient/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "piranha",
    id: 6553,
    node_id: "MDQ6VXNlcjY1NTM=",
    avatar_url: "https://avatars2.githubusercontent.com/u/6553?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/piranha",
    html_url: "https://github.com/piranha",
    followers_url: "https://api.github.com/users/piranha/followers",
    following_url: "https://api.github.com/users/piranha/following{/other_user}",
    gists_url: "https://api.github.com/users/piranha/gists{/gist_id}",
    starred_url: "https://api.github.com/users/piranha/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/piranha/subscriptions",
    organizations_url: "https://api.github.com/users/piranha/orgs",
    repos_url: "https://api.github.com/users/piranha/repos",
    events_url: "https://api.github.com/users/piranha/events{/privacy}",
    received_events_url: "https://api.github.com/users/piranha/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "sophiebits",
    id: 6820,
    node_id: "MDQ6VXNlcjY4MjA=",
    avatar_url: "https://avatars2.githubusercontent.com/u/6820?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sophiebits",
    html_url: "https://github.com/sophiebits",
    followers_url: "https://api.github.com/users/sophiebits/followers",
    following_url: "https://api.github.com/users/sophiebits/following{/other_user}",
    gists_url: "https://api.github.com/users/sophiebits/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sophiebits/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sophiebits/subscriptions",
    organizations_url: "https://api.github.com/users/sophiebits/orgs",
    repos_url: "https://api.github.com/users/sophiebits/repos",
    events_url: "https://api.github.com/users/sophiebits/events{/privacy}",
    received_events_url: "https://api.github.com/users/sophiebits/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "zpao",
    id: 8445,
    node_id: "MDQ6VXNlcjg0NDU=",
    avatar_url: "https://avatars1.githubusercontent.com/u/8445?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/zpao",
    html_url: "https://github.com/zpao",
    followers_url: "https://api.github.com/users/zpao/followers",
    following_url: "https://api.github.com/users/zpao/following{/other_user}",
    gists_url: "https://api.github.com/users/zpao/gists{/gist_id}",
    starred_url: "https://api.github.com/users/zpao/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/zpao/subscriptions",
    organizations_url: "https://api.github.com/users/zpao/orgs",
    repos_url: "https://api.github.com/users/zpao/repos",
    events_url: "https://api.github.com/users/zpao/events{/privacy}",
    received_events_url: "https://api.github.com/users/zpao/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "spoike",
    id: 9253,
    node_id: "MDQ6VXNlcjkyNTM=",
    avatar_url: "https://avatars0.githubusercontent.com/u/9253?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/spoike",
    html_url: "https://github.com/spoike",
    followers_url: "https://api.github.com/users/spoike/followers",
    following_url: "https://api.github.com/users/spoike/following{/other_user}",
    gists_url: "https://api.github.com/users/spoike/gists{/gist_id}",
    starred_url: "https://api.github.com/users/spoike/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/spoike/subscriptions",
    organizations_url: "https://api.github.com/users/spoike/orgs",
    repos_url: "https://api.github.com/users/spoike/repos",
    events_url: "https://api.github.com/users/spoike/events{/privacy}",
    received_events_url: "https://api.github.com/users/spoike/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "goatslacker",
    id: 10632,
    node_id: "MDQ6VXNlcjEwNjMy",
    avatar_url: "https://avatars1.githubusercontent.com/u/10632?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/goatslacker",
    html_url: "https://github.com/goatslacker",
    followers_url: "https://api.github.com/users/goatslacker/followers",
    following_url: "https://api.github.com/users/goatslacker/following{/other_user}",
    gists_url: "https://api.github.com/users/goatslacker/gists{/gist_id}",
    starred_url: "https://api.github.com/users/goatslacker/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/goatslacker/subscriptions",
    organizations_url: "https://api.github.com/users/goatslacker/orgs",
    repos_url: "https://api.github.com/users/goatslacker/repos",
    events_url: "https://api.github.com/users/goatslacker/events{/privacy}",
    received_events_url: "https://api.github.com/users/goatslacker/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "simenbrekken",
    id: 12807,
    node_id: "MDQ6VXNlcjEyODA3",
    avatar_url: "https://avatars3.githubusercontent.com/u/12807?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/simenbrekken",
    html_url: "https://github.com/simenbrekken",
    followers_url: "https://api.github.com/users/simenbrekken/followers",
    following_url: "https://api.github.com/users/simenbrekken/following{/other_user}",
    gists_url: "https://api.github.com/users/simenbrekken/gists{/gist_id}",
    starred_url: "https://api.github.com/users/simenbrekken/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/simenbrekken/subscriptions",
    organizations_url: "https://api.github.com/users/simenbrekken/orgs",
    repos_url: "https://api.github.com/users/simenbrekken/repos",
    events_url: "https://api.github.com/users/simenbrekken/events{/privacy}",
    received_events_url: "https://api.github.com/users/simenbrekken/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "rauchg",
    id: 13041,
    node_id: "MDQ6VXNlcjEzMDQx",
    avatar_url: "https://avatars0.githubusercontent.com/u/13041?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rauchg",
    html_url: "https://github.com/rauchg",
    followers_url: "https://api.github.com/users/rauchg/followers",
    following_url: "https://api.github.com/users/rauchg/following{/other_user}",
    gists_url: "https://api.github.com/users/rauchg/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rauchg/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rauchg/subscriptions",
    organizations_url: "https://api.github.com/users/rauchg/orgs",
    repos_url: "https://api.github.com/users/rauchg/repos",
    events_url: "https://api.github.com/users/rauchg/events{/privacy}",
    received_events_url: "https://api.github.com/users/rauchg/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "steveluscher",
    id: 13243,
    node_id: "MDQ6VXNlcjEzMjQz",
    avatar_url: "https://avatars1.githubusercontent.com/u/13243?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/steveluscher",
    html_url: "https://github.com/steveluscher",
    followers_url: "https://api.github.com/users/steveluscher/followers",
    following_url: "https://api.github.com/users/steveluscher/following{/other_user}",
    gists_url: "https://api.github.com/users/steveluscher/gists{/gist_id}",
    starred_url: "https://api.github.com/users/steveluscher/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/steveluscher/subscriptions",
    organizations_url: "https://api.github.com/users/steveluscher/orgs",
    repos_url: "https://api.github.com/users/steveluscher/repos",
    events_url: "https://api.github.com/users/steveluscher/events{/privacy}",
    received_events_url: "https://api.github.com/users/steveluscher/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "cpojer",
    id: 13352,
    node_id: "MDQ6VXNlcjEzMzUy",
    avatar_url: "https://avatars0.githubusercontent.com/u/13352?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/cpojer",
    html_url: "https://github.com/cpojer",
    followers_url: "https://api.github.com/users/cpojer/followers",
    following_url: "https://api.github.com/users/cpojer/following{/other_user}",
    gists_url: "https://api.github.com/users/cpojer/gists{/gist_id}",
    starred_url: "https://api.github.com/users/cpojer/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/cpojer/subscriptions",
    organizations_url: "https://api.github.com/users/cpojer/orgs",
    repos_url: "https://api.github.com/users/cpojer/repos",
    events_url: "https://api.github.com/users/cpojer/events{/privacy}",
    received_events_url: "https://api.github.com/users/cpojer/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "swannodette",
    id: 13516,
    node_id: "MDQ6VXNlcjEzNTE2",
    avatar_url: "https://avatars0.githubusercontent.com/u/13516?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/swannodette",
    html_url: "https://github.com/swannodette",
    followers_url: "https://api.github.com/users/swannodette/followers",
    following_url: "https://api.github.com/users/swannodette/following{/other_user}",
    gists_url: "https://api.github.com/users/swannodette/gists{/gist_id}",
    starred_url: "https://api.github.com/users/swannodette/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/swannodette/subscriptions",
    organizations_url: "https://api.github.com/users/swannodette/orgs",
    repos_url: "https://api.github.com/users/swannodette/repos",
    events_url: "https://api.github.com/users/swannodette/events{/privacy}",
    received_events_url: "https://api.github.com/users/swannodette/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "ericclemmons",
    id: 15182,
    node_id: "MDQ6VXNlcjE1MTgy",
    avatar_url: "https://avatars0.githubusercontent.com/u/15182?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ericclemmons",
    html_url: "https://github.com/ericclemmons",
    followers_url: "https://api.github.com/users/ericclemmons/followers",
    following_url: "https://api.github.com/users/ericclemmons/following{/other_user}",
    gists_url: "https://api.github.com/users/ericclemmons/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ericclemmons/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ericclemmons/subscriptions",
    organizations_url: "https://api.github.com/users/ericclemmons/orgs",
    repos_url: "https://api.github.com/users/ericclemmons/repos",
    events_url: "https://api.github.com/users/ericclemmons/events{/privacy}",
    received_events_url: "https://api.github.com/users/ericclemmons/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "jeroencoumans",
    id: 15248,
    node_id: "MDQ6VXNlcjE1MjQ4",
    avatar_url: "https://avatars3.githubusercontent.com/u/15248?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jeroencoumans",
    html_url: "https://github.com/jeroencoumans",
    followers_url: "https://api.github.com/users/jeroencoumans/followers",
    following_url: "https://api.github.com/users/jeroencoumans/following{/other_user}",
    gists_url: "https://api.github.com/users/jeroencoumans/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jeroencoumans/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jeroencoumans/subscriptions",
    organizations_url: "https://api.github.com/users/jeroencoumans/orgs",
    repos_url: "https://api.github.com/users/jeroencoumans/repos",
    events_url: "https://api.github.com/users/jeroencoumans/events{/privacy}",
    received_events_url: "https://api.github.com/users/jeroencoumans/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "jlongster",
    id: 17031,
    node_id: "MDQ6VXNlcjE3MDMx",
    avatar_url: "https://avatars2.githubusercontent.com/u/17031?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jlongster",
    html_url: "https://github.com/jlongster",
    followers_url: "https://api.github.com/users/jlongster/followers",
    following_url: "https://api.github.com/users/jlongster/following{/other_user}",
    gists_url: "https://api.github.com/users/jlongster/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jlongster/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jlongster/subscriptions",
    organizations_url: "https://api.github.com/users/jlongster/orgs",
    repos_url: "https://api.github.com/users/jlongster/repos",
    events_url: "https://api.github.com/users/jlongster/events{/privacy}",
    received_events_url: "https://api.github.com/users/jlongster/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "threepointone",
    id: 18808,
    node_id: "MDQ6VXNlcjE4ODA4",
    avatar_url: "https://avatars2.githubusercontent.com/u/18808?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/threepointone",
    html_url: "https://github.com/threepointone",
    followers_url: "https://api.github.com/users/threepointone/followers",
    following_url: "https://api.github.com/users/threepointone/following{/other_user}",
    gists_url: "https://api.github.com/users/threepointone/gists{/gist_id}",
    starred_url: "https://api.github.com/users/threepointone/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/threepointone/subscriptions",
    organizations_url: "https://api.github.com/users/threepointone/orgs",
    repos_url: "https://api.github.com/users/threepointone/repos",
    events_url: "https://api.github.com/users/threepointone/events{/privacy}",
    received_events_url: "https://api.github.com/users/threepointone/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "haacked",
    id: 19977,
    node_id: "MDQ6VXNlcjE5OTc3",
    avatar_url: "https://avatars1.githubusercontent.com/u/19977?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/haacked",
    html_url: "https://github.com/haacked",
    followers_url: "https://api.github.com/users/haacked/followers",
    following_url: "https://api.github.com/users/haacked/following{/other_user}",
    gists_url: "https://api.github.com/users/haacked/gists{/gist_id}",
    starred_url: "https://api.github.com/users/haacked/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/haacked/subscriptions",
    organizations_url: "https://api.github.com/users/haacked/orgs",
    repos_url: "https://api.github.com/users/haacked/repos",
    events_url: "https://api.github.com/users/haacked/events{/privacy}",
    received_events_url: "https://api.github.com/users/haacked/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "rickharrison",
    id: 22048,
    node_id: "MDQ6VXNlcjIyMDQ4",
    avatar_url: "https://avatars2.githubusercontent.com/u/22048?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rickharrison",
    html_url: "https://github.com/rickharrison",
    followers_url: "https://api.github.com/users/rickharrison/followers",
    following_url: "https://api.github.com/users/rickharrison/following{/other_user}",
    gists_url: "https://api.github.com/users/rickharrison/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rickharrison/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rickharrison/subscriptions",
    organizations_url: "https://api.github.com/users/rickharrison/orgs",
    repos_url: "https://api.github.com/users/rickharrison/repos",
    events_url: "https://api.github.com/users/rickharrison/events{/privacy}",
    received_events_url: "https://api.github.com/users/rickharrison/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "patcito",
    id: 26435,
    node_id: "MDQ6VXNlcjI2NDM1",
    avatar_url: "https://avatars2.githubusercontent.com/u/26435?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/patcito",
    html_url: "https://github.com/patcito",
    followers_url: "https://api.github.com/users/patcito/followers",
    following_url: "https://api.github.com/users/patcito/following{/other_user}",
    gists_url: "https://api.github.com/users/patcito/gists{/gist_id}",
    starred_url: "https://api.github.com/users/patcito/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/patcito/subscriptions",
    organizations_url: "https://api.github.com/users/patcito/orgs",
    repos_url: "https://api.github.com/users/patcito/repos",
    events_url: "https://api.github.com/users/patcito/events{/privacy}",
    received_events_url: "https://api.github.com/users/patcito/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "andreypopp",
    id: 30594,
    node_id: "MDQ6VXNlcjMwNTk0",
    avatar_url: "https://avatars0.githubusercontent.com/u/30594?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/andreypopp",
    html_url: "https://github.com/andreypopp",
    followers_url: "https://api.github.com/users/andreypopp/followers",
    following_url: "https://api.github.com/users/andreypopp/following{/other_user}",
    gists_url: "https://api.github.com/users/andreypopp/gists{/gist_id}",
    starred_url: "https://api.github.com/users/andreypopp/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/andreypopp/subscriptions",
    organizations_url: "https://api.github.com/users/andreypopp/orgs",
    repos_url: "https://api.github.com/users/andreypopp/repos",
    events_url: "https://api.github.com/users/andreypopp/events{/privacy}",
    received_events_url: "https://api.github.com/users/andreypopp/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "tmcw",
    id: 32314,
    node_id: "MDQ6VXNlcjMyMzE0",
    avatar_url: "https://avatars2.githubusercontent.com/u/32314?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tmcw",
    html_url: "https://github.com/tmcw",
    followers_url: "https://api.github.com/users/tmcw/followers",
    following_url: "https://api.github.com/users/tmcw/following{/other_user}",
    gists_url: "https://api.github.com/users/tmcw/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tmcw/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tmcw/subscriptions",
    organizations_url: "https://api.github.com/users/tmcw/orgs",
    repos_url: "https://api.github.com/users/tmcw/repos",
    events_url: "https://api.github.com/users/tmcw/events{/privacy}",
    received_events_url: "https://api.github.com/users/tmcw/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "nelix",
    id: 33324,
    node_id: "MDQ6VXNlcjMzMzI0",
    avatar_url: "https://avatars2.githubusercontent.com/u/33324?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nelix",
    html_url: "https://github.com/nelix",
    followers_url: "https://api.github.com/users/nelix/followers",
    following_url: "https://api.github.com/users/nelix/following{/other_user}",
    gists_url: "https://api.github.com/users/nelix/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nelix/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nelix/subscriptions",
    organizations_url: "https://api.github.com/users/nelix/orgs",
    repos_url: "https://api.github.com/users/nelix/repos",
    events_url: "https://api.github.com/users/nelix/events{/privacy}",
    received_events_url: "https://api.github.com/users/nelix/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "arnihermann",
    id: 35656,
    node_id: "MDQ6VXNlcjM1NjU2",
    avatar_url: "https://avatars2.githubusercontent.com/u/35656?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/arnihermann",
    html_url: "https://github.com/arnihermann",
    followers_url: "https://api.github.com/users/arnihermann/followers",
    following_url: "https://api.github.com/users/arnihermann/following{/other_user}",
    gists_url: "https://api.github.com/users/arnihermann/gists{/gist_id}",
    starred_url: "https://api.github.com/users/arnihermann/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/arnihermann/subscriptions",
    organizations_url: "https://api.github.com/users/arnihermann/orgs",
    repos_url: "https://api.github.com/users/arnihermann/repos",
    events_url: "https://api.github.com/users/arnihermann/events{/privacy}",
    received_events_url: "https://api.github.com/users/arnihermann/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "migueldeicaza",
    id: 36863,
    node_id: "MDQ6VXNlcjM2ODYz",
    avatar_url: "https://avatars2.githubusercontent.com/u/36863?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/migueldeicaza",
    html_url: "https://github.com/migueldeicaza",
    followers_url: "https://api.github.com/users/migueldeicaza/followers",
    following_url: "https://api.github.com/users/migueldeicaza/following{/other_user}",
    gists_url: "https://api.github.com/users/migueldeicaza/gists{/gist_id}",
    starred_url: "https://api.github.com/users/migueldeicaza/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/migueldeicaza/subscriptions",
    organizations_url: "https://api.github.com/users/migueldeicaza/orgs",
    repos_url: "https://api.github.com/users/migueldeicaza/repos",
    events_url: "https://api.github.com/users/migueldeicaza/events{/privacy}",
    received_events_url: "https://api.github.com/users/migueldeicaza/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "nzakas",
    id: 38546,
    node_id: "MDQ6VXNlcjM4NTQ2",
    avatar_url: "https://avatars3.githubusercontent.com/u/38546?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nzakas",
    html_url: "https://github.com/nzakas",
    followers_url: "https://api.github.com/users/nzakas/followers",
    following_url: "https://api.github.com/users/nzakas/following{/other_user}",
    gists_url: "https://api.github.com/users/nzakas/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nzakas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nzakas/subscriptions",
    organizations_url: "https://api.github.com/users/nzakas/orgs",
    repos_url: "https://api.github.com/users/nzakas/repos",
    events_url: "https://api.github.com/users/nzakas/events{/privacy}",
    received_events_url: "https://api.github.com/users/nzakas/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "itrelease",
    id: 41234,
    node_id: "MDQ6VXNlcjQxMjM0",
    avatar_url: "https://avatars3.githubusercontent.com/u/41234?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/itrelease",
    html_url: "https://github.com/itrelease",
    followers_url: "https://api.github.com/users/itrelease/followers",
    following_url: "https://api.github.com/users/itrelease/following{/other_user}",
    gists_url: "https://api.github.com/users/itrelease/gists{/gist_id}",
    starred_url: "https://api.github.com/users/itrelease/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/itrelease/subscriptions",
    organizations_url: "https://api.github.com/users/itrelease/orgs",
    repos_url: "https://api.github.com/users/itrelease/repos",
    events_url: "https://api.github.com/users/itrelease/events{/privacy}",
    received_events_url: "https://api.github.com/users/itrelease/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "tcoopman",
    id: 45546,
    node_id: "MDQ6VXNlcjQ1NTQ2",
    avatar_url: "https://avatars3.githubusercontent.com/u/45546?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tcoopman",
    html_url: "https://github.com/tcoopman",
    followers_url: "https://api.github.com/users/tcoopman/followers",
    following_url: "https://api.github.com/users/tcoopman/following{/other_user}",
    gists_url: "https://api.github.com/users/tcoopman/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tcoopman/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tcoopman/subscriptions",
    organizations_url: "https://api.github.com/users/tcoopman/orgs",
    repos_url: "https://api.github.com/users/tcoopman/repos",
    events_url: "https://api.github.com/users/tcoopman/events{/privacy}",
    received_events_url: "https://api.github.com/users/tcoopman/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "mattpodwysocki",
    id: 49051,
    node_id: "MDQ6VXNlcjQ5MDUx",
    avatar_url: "https://avatars2.githubusercontent.com/u/49051?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mattpodwysocki",
    html_url: "https://github.com/mattpodwysocki",
    followers_url: "https://api.github.com/users/mattpodwysocki/followers",
    following_url: "https://api.github.com/users/mattpodwysocki/following{/other_user}",
    gists_url: "https://api.github.com/users/mattpodwysocki/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mattpodwysocki/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mattpodwysocki/subscriptions",
    organizations_url: "https://api.github.com/users/mattpodwysocki/orgs",
    repos_url: "https://api.github.com/users/mattpodwysocki/repos",
    events_url: "https://api.github.com/users/mattpodwysocki/events{/privacy}",
    received_events_url: "https://api.github.com/users/mattpodwysocki/received_events",
    type: "User",
    site_admin: true
    }
];
    